json.id                token.id
json.name              token.name
json.symbol            token.symbol
json.description       token.description
json.effect_type       token.effect_type
json.inscribed_effect  token.inscribed_effect
json.oathbound_effect  token.oathbound_effect
json.offering_effect   token.offering_effect
json.lore_token        token.lore_token
